import { useCallback, useEffect, useMemo, useState } from 'react';
import { riderService } from '../../services/resource.service';
import { getSocket } from '../../services/socket';
import { DriverOnboardingModal } from './DriverOnboardingModal';

const tabs = [
  ['Overview', 'Identity & dispatch'],
  ['KYC', 'Documents & approval'],
  ['Security', 'Alerts, fines & GPS'],
  ['Orders', 'Assigned deliveries'],
  ['Finance', 'Earnings & payments'],
  ['Support', 'Incidents & tickets'],
];
const availabilityOptions = ['AVAILABLE', 'ON_DELIVERY', 'BREAK', 'OFFLINE'];
const cancelled = error => error?.code === 'ERR_CANCELED' || error?.name === 'CanceledError';
const errorMessage = (error, fallback) => error?.response?.data?.message || fallback;
const title = value => String(value || 'Not set').toLowerCase().split('_').map(word => word ? word[0].toUpperCase() + word.slice(1) : '').join(' ');
const money = value => `UGX ${Number(value || 0).toLocaleString()}`;
const date = value => value ? new Date(value).toLocaleString() : 'Not recorded';

function Pill({ children, className = '' }) { return <span className={`rider-pill ${className}`}>{children}</span>; }
function EmptyRecords({ title: heading, children }) { return <div className="rider-empty-records"><b>{heading}</b><span>{children}</span></div>; }
function Field({ label, value }) { return <div className="rider-data-field"><span>{label}</span><b>{value ?? 'Not set'}</b></div>; }
function PanelHeading({ eyebrow, title: heading, description, action }) { return <div className="rider-section-title"><div><span>{eyebrow}</span><h2>{heading}</h2><p>{description}</p></div>{action}</div>; }

function Overview({ rider, workspace, onUpdate, onDelete, busy }) {
  if (!rider) return <section className="rider-panel"><EmptyRecords title="No drivers found">Add a driver to begin onboarding.</EmptyRecords></section>;
  const tracking = workspace?.latestTracking;
  const coordinates = tracking?.location?.coordinates || rider.currentLocation?.coordinates;
  const location = coordinates ? { lng: coordinates[0], lat: coordinates[1], updatedAt: tracking?.recordedAt || rider.lastHeartbeatAt } : null;
  const vehicle = workspace?.vehicle;
  const gps = workspace?.gpsDevice;
  const acceptance = workspace?.metrics?.acceptanceRate ?? rider.acceptanceRate ?? 0;
  return <section className="rider-account rider-panel">
    <PanelHeading eyebrow="Rider account and status" title="Live backend rider state" description="Identity, hub assignment, GPS, and dispatch controls from the shared MongoDB records." action={<Pill>{title(rider.availability)}</Pill>} />
    <div className="selected-rider">
      <div className="selected-head"><div><span>Selected rider</span><b>{rider.name}</b><small>{rider.driverCode || 'Driver code pending'}</small></div><div className="rider-actions"><Pill>{rider.kycStatus}{rider.locked ? ' · Restricted' : ''}</Pill><button disabled={busy} onClick={() => onUpdate({ status: rider.status === 'ACTIVE' ? 'SUSPENDED' : 'ACTIVE' })}>{rider.status === 'ACTIVE' ? 'Suspend rider' : 'Approve for dispatch'}</button><button disabled={busy} className="delete" onClick={onDelete}>Delete rider</button></div></div>
      <div className="performance-box"><div className="performance-title"><div><span>Performance-based dispatch</span><p>Shared delivery metrics used for dispatch decisions.</p></div><Pill className="priority">Acceptance {acceptance}%</Pill></div><div className="rider-metrics"><Field label="Deliveries" value={rider.completedDeliveries || 0} /><Field label="Acceptance" value={`${acceptance}%`} /><Field label="Rating" value={`${Number(rider.rating || 0).toFixed(1)}/5`} /><Field label="COD held" value={money(rider.codHeld)} /></div></div>
      <div className="profile-box"><div><span>Operational profile</span><p>Admin-managed identity, stage, and vehicle information.</p></div><div className="profile-inputs rider-field-grid"><Field label="Full name" value={rider.name} /><Field label="Phone" value={rider.phone} /><Field label="Boda stage" value={rider.stage || 'Not set'} /><Field label="Driver code" value={rider.driverCode || 'Not set'} /><Field label="Vehicle" value={vehicle ? `${title(vehicle.type)} · ${vehicle.plateNumber}` : rider.plateNumber || 'Not assigned'} /><Field label="Experience" value={`${Number(rider.yearsExperience || 0)} years`} /></div></div>
      <div className="driver-control-row"><label className="driver-control-field"><span>Dispatch availability</span><select disabled={busy || rider.status !== 'ACTIVE'} value={rider.availability || 'OFFLINE'} onChange={event => onUpdate({ availability: event.target.value })}>{availabilityOptions.map(option => <option value={option} key={option}>{title(option)}</option>)}</select><small>{rider.status === 'ACTIVE' ? 'Controls whether dispatch can assign work.' : 'Approve the rider before changing availability.'}</small></label><label className="driver-toggle"><input type="checkbox" checked={Boolean(rider.autoAccept)} disabled={busy || rider.status !== 'ACTIVE'} onChange={event => onUpdate({ autoAccept: event.target.checked })} /><span><b>Auto-accept assignments</b><small>Automatically accept eligible dispatch jobs.</small></span></label></div>
    </div>
    <div className="rider-status-grid"><div className="status-card"><div className="status-title"><i>ID</i><div><b>Authenticated rider</b><span>Identity and compliance snapshot</span></div><Pill className={rider.status === 'ACTIVE' ? 'verified' : ''}>{rider.kycStatus}</Pill></div><div className="identity-grid"><Field label="Phone" value={rider.phone} /><Field label="Email" value={workspace?.user?.email || rider.email || 'Not set'} /><Field label="District" value={rider.district || 'Not set'} /><Field label="National ID" value={rider.nationalId || 'Not set'} /><Field label="Account status" value={title(rider.status)} /></div></div><div className="status-card"><div className="status-title"><i>GPS</i><div><b>Status and GPS</b><span>Availability and latest authorized location</span></div><Pill className={location ? 'verified' : ''}>{location ? 'Tracking live' : 'No fix'}</Pill></div><div className="gps-facts"><Field label="Coordinates" value={location ? `${location.lat}, ${location.lng}` : 'Unavailable'} /><Field label="Last update" value={location ? date(location.updatedAt) : 'Never'} /><Field label="Tracker" value={gps?.serialNumber || 'Not assigned'} /><Field label="Battery" value={gps?.battery == null ? 'Unavailable' : `${gps.battery}%`} /></div></div></div>
  </section>;
}

function KycPanel({ rider, workspace, onUpdate, busy }) {
  const documents = workspace?.kycDocuments || [];
  return <section className="rider-panel"><PanelHeading eyebrow="KYC and approval" title="Driver compliance review" description="Verify the identity record and uploaded documents before enabling dispatch." action={<button className="rider-primary-action" disabled={busy || rider?.status === 'ACTIVE'} onClick={() => onUpdate({ status: 'ACTIVE' })}>{rider?.status === 'ACTIVE' ? 'Approved' : 'Approve driver'}</button>} /><div className="rider-field-grid"><Field label="Current status" value={rider?.kycStatus} /><Field label="National ID / passport" value={rider?.nationalId || 'Not supplied'} /><Field label="Legal acceptance" value={rider?.status === 'PENDING_LEGAL' ? 'Pending' : 'Confirmed'} /><Field label="Documents" value={`${documents.length} uploaded`} /></div><div className="rider-record-section"><h3>Uploaded documents</h3>{documents.length ? <div className="rider-record-grid">{documents.map(document => <article key={document._id}><div><b>{title(document.documentType)}</b><span>{document.verifiedAt ? 'Verified' : document.rejectedAt ? 'Rejected' : 'Pending review'}</span></div>{document.document?.url && <a href={document.document.url} target="_blank" rel="noreferrer">Open document</a>}</article>)}</div> : <EmptyRecords title="No KYC documents uploaded">The driver stays restricted until the required documents are submitted and reviewed.</EmptyRecords>}</div></section>;
}

function SecurityPanel({ rider, workspace }) {
  const alerts = workspace?.alerts || [], fines = workspace?.fines || [];
  return <section className="rider-panel"><PanelHeading eyebrow="Security and compliance" title="Risk, GPS, and bond controls" description="Live security alerts, penalties, emergency contact, and tracker health." action={<Pill className={alerts.some(item => item.status === 'OPEN') ? 'danger' : 'verified'}>{workspace?.metrics?.openAlerts || 0} open alerts</Pill>} /><div className="rider-field-grid"><Field label="Security bond" value={money(rider?.securityBond)} /><Field label="Total fines" value={money(workspace?.metrics?.totalFines ?? rider?.finesTotal)} /><Field label="Next of kin" value={rider?.nextOfKin?.name || 'Not set'} /><Field label="Emergency phone" value={rider?.nextOfKin?.phone || 'Not set'} /><Field label="GPS device" value={workspace?.gpsDevice?.serialNumber || 'Not assigned'} /><Field label="Last heartbeat" value={date(workspace?.gpsDevice?.lastHeartbeatAt || rider?.lastHeartbeatAt)} /></div><div className="rider-split-records"><div className="rider-record-section"><h3>Security alerts</h3>{alerts.length ? alerts.map(item => <article className="rider-record-row" key={item._id}><div><b>{title(item.type)}</b><span>{item.severity} · {date(item.createdAt)}</span></div><Pill>{title(item.status)}</Pill></article>) : <EmptyRecords title="No security alerts">No security events are attached to this rider.</EmptyRecords>}</div><div className="rider-record-section"><h3>Fines and penalties</h3>{fines.length ? fines.map(item => <article className="rider-record-row" key={item._id}><div><b>{item.reason}</b><span>{title(item.deductedFrom)} · {date(item.appliedAt || item.createdAt)}</span></div><strong>{money(item.amount)}</strong></article>) : <EmptyRecords title="No penalties">No fines have been recorded for this rider.</EmptyRecords>}</div></div></section>;
}

function OrdersPanel({ workspace }) {
  const orders = workspace?.orders || [];
  return <section className="rider-panel"><PanelHeading eyebrow="Assigned work" title="Rider order history" description="The latest assigned deliveries from the shared orders collection." action={<Pill>{orders.length} orders</Pill>} />{orders.length ? <div className="rider-order-list">{orders.map(order => <article key={order._id}><div><b>{order.orderNumber}</b><span>{order.customer?.name || 'Customer'} · {order.delivery?.address || 'Delivery address not set'}</span></div><div><Pill>{title(order.orderStatus)}</Pill><strong>{money(order.codAmount || order.pricing?.total)}</strong><small>{date(order.createdAt)}</small></div></article>)}</div> : <EmptyRecords title="No assigned orders">Orders assigned through dispatch will appear here.</EmptyRecords>}</section>;
}

function FinancePanel({ rider, workspace }) {
  const earnings = workspace?.earnings || [], payments = workspace?.payments || [];
  return <section className="rider-panel"><PanelHeading eyebrow="Driver finance" title="Earnings, COD, and settlements" description="Finance records are read from driver earnings, payments, fines, and COD exposure." /><div className="rider-finance-metrics"><Field label="Recorded earnings" value={money(workspace?.metrics?.totalEarnings)} /><Field label="Daily earnings" value={money(rider?.dailyEarnings)} /><Field label="COD held" value={money(rider?.codHeld)} /><Field label="Fines" value={money(workspace?.metrics?.totalFines ?? rider?.finesTotal)} /></div><div className="rider-split-records"><div className="rider-record-section"><h3>Earnings</h3>{earnings.length ? earnings.map(item => <article className="rider-record-row" key={item._id}><div><b>{title(item.type)}</b><span>{item.businessDate}</span></div><strong>{money(item.amount)}</strong></article>) : <EmptyRecords title="No earnings yet">Completed paid deliveries will create earning records.</EmptyRecords>}</div><div className="rider-record-section"><h3>Payments</h3>{payments.length ? payments.map(item => <article className="rider-record-row" key={item._id}><div><b>{item.paymentNumber || title(item.type)}</b><span>{title(item.status)} · {date(item.paidAt || item.createdAt)}</span></div><strong>{money(item.amount)}</strong></article>) : <EmptyRecords title="No payments yet">Settlement transactions will appear here.</EmptyRecords>}</div></div></section>;
}

function SupportPanel({ workspace }) {
  const incidents = workspace?.incidents || [], tickets = workspace?.tickets || [];
  return <section className="rider-panel"><PanelHeading eyebrow="Operations support" title="Incidents and support cases" description="Operational issues linked to this rider and tickets assigned to the rider account." action={<Pill>{workspace?.metrics?.openIncidents || 0} open incidents</Pill>} /><div className="rider-split-records"><div className="rider-record-section"><h3>Incidents</h3>{incidents.length ? incidents.map(item => <article className="rider-record-row" key={item._id}><div><b>{item.incidentNumber} · {title(item.type)}</b><span>{item.description}</span></div><Pill>{item.resolvedAt ? 'Resolved' : title(item.status)}</Pill></article>) : <EmptyRecords title="No incidents">No operational incidents are linked to this rider.</EmptyRecords>}</div><div className="rider-record-section"><h3>Support tickets</h3>{tickets.length ? tickets.map(item => <article className="rider-record-row" key={item._id}><div><b>{item.subject}</b><span>{item.message}</span></div><Pill>{title(item.status)}</Pill></article>) : <EmptyRecords title="No support tickets">Assigned support cases will appear here.</EmptyRecords>}</div></div></section>;
}

export function RidersPage() {
  const [riders, setRiders] = useState([]), [selectedId, setSelectedId] = useState(''), [active, setActive] = useState('Overview'), [workspace, setWorkspace] = useState(null), [loading, setLoading] = useState(true), [workspaceLoading, setWorkspaceLoading] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [panelError, setPanelError] = useState(''), [showOnboarding, setShowOnboarding] = useState(false);
  useEffect(() => { const controller = new AbortController(); setLoading(true); riderService.list({}, controller.signal).then(items => { setRiders(items); setSelectedId(current => items.some(item => item._id === current) ? current : items[0]?._id || ''); setError(''); }).catch(loadError => { if (!cancelled(loadError)) setError(errorMessage(loadError, 'Riders could not be loaded.')); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, []);
  const loadWorkspace = useCallback(async (id, signal, showLoading = true) => { if (!id) { setWorkspace(null); return null; } if (showLoading) setWorkspaceLoading(true); try { const result = await riderService.workspace(id, signal); setWorkspace(result); setPanelError(''); setRiders(items => items.map(item => item._id === id ? result.driver : item)); return result; } catch (loadError) { if (!cancelled(loadError)) { setPanelError(errorMessage(loadError, 'The rider workspace could not be loaded.')); if (showLoading) setWorkspace(null); } return null; } finally { if (showLoading && !signal?.aborted) setWorkspaceLoading(false); } }, []);
  useEffect(() => { const controller = new AbortController(); loadWorkspace(selectedId, controller.signal); return () => controller.abort(); }, [selectedId, loadWorkspace]);
  useEffect(() => {
    if (!selectedId) return undefined;
    const socket = getSocket();
    let refreshTimer;
    const refresh = payload => {
      if (payload?.driverId && String(payload.driverId) !== String(selectedId)) return;
      window.clearTimeout(refreshTimer);
      refreshTimer = window.setTimeout(() => loadWorkspace(selectedId, undefined, false), 200);
    };
    const events = ['driverLocation', 'orderAssigned', 'orderStatusChanged', 'orderDelivered', 'dashboardUpdated', 'trackerTampered', 'incidentReported'];
    events.forEach(event => socket?.on(event, refresh));
    socket?.connect();
    const poll = window.setInterval(() => loadWorkspace(selectedId, undefined, false), 30_000);
    return () => { window.clearTimeout(refreshTimer); window.clearInterval(poll); events.forEach(event => socket?.off(event, refresh)); };
  }, [selectedId, loadWorkspace]);
  const rider = useMemo(() => riders.find(item => item._id === selectedId) || riders[0], [riders, selectedId]);
  function created(item) { setRiders(items => [item, ...items.filter(value => value._id !== item._id)]); setSelectedId(item._id); setActive('Overview'); setShowOnboarding(false); }
  async function update(payload) { if (!rider || busy) return; setBusy(true); setPanelError(''); try { const item = await riderService.update(rider._id, payload); setRiders(items => items.map(value => value._id === item._id ? { ...value, ...item } : value)); await loadWorkspace(item._id); } catch (updateError) { setPanelError(errorMessage(updateError, 'The rider could not be updated.')); } finally { setBusy(false); } }
  async function remove() { if (!rider || !window.confirm(`Delete ${rider.name}?`)) return; setBusy(true); try { await riderService.remove(rider._id); const next = riders.filter(item => item._id !== rider._id); setRiders(next); setSelectedId(next[0]?._id || ''); setWorkspace(null); } catch (deleteError) { setPanelError(errorMessage(deleteError, 'The rider could not be deleted.')); } finally { setBusy(false); } }
  const activeRiders = riders.filter(item => item.status === 'ACTIVE' && item.availability !== 'OFFLINE').length;
  const tabProps = { rider, workspace, onUpdate: update, onDelete: remove, busy };
  const panel = active === 'Overview' ? <Overview {...tabProps} /> : active === 'KYC' ? <KycPanel {...tabProps} /> : active === 'Security' ? <SecurityPanel {...tabProps} /> : active === 'Orders' ? <OrdersPanel {...tabProps} /> : active === 'Finance' ? <FinancePanel {...tabProps} /> : <SupportPanel {...tabProps} />;
  return <div className="riders-page"><section className="onboard-card"><div><span>Driver administration</span><h2>Onboard drivers from the Admin Panel</h2><p>Create the rider profile and login together. New drivers remain restricted until KYC and admin approval.</p></div><button onClick={() => setShowOnboarding(true)}>+ &nbsp; Add driver</button></section>{error && <div className="warning-note" role="alert">{error}</div>}<div className="rider-summary"><div><span>Active riders</span><b>{activeRiders}</b></div><div><span>Tracker alerts</span><b className="red-value">{riders.filter(item => !item.currentLocation && !item.lastHeartbeatAt).length}</b></div><div><span>COD carried</span><b className="amber-value">{money(riders.reduce((sum, item) => sum + Number(item.codHeld || 0), 0))}</b></div><div><span>Completed</span><b className="green-value">{riders.reduce((sum, item) => sum + Number(item.completedDeliveries || 0), 0)}</b></div></div><section className="roster-card"><div className="roster-title"><div><span>Driver roster</span><h2>Select the rider to inspect</h2></div><p>{riders.length} {riders.length === 1 ? 'rider' : 'riders'}</p></div>{loading ? <EmptyRecords title="Loading riders">Fetching the authorized hub roster.</EmptyRecords> : <div className="rider-list">{riders.map(item => <button className={rider?._id === item._id ? 'active' : ''} onClick={() => setSelectedId(item._id)} key={item._id}><b>{item.name}</b><span>{item.plateNumber || item.driverCode || 'Vehicle not assigned'}</span><small className={item.status !== 'ACTIVE' ? 'pending' : ''}>{item.kycStatus}{item.locked ? ' · Restricted' : ''}</small></button>)}</div>}</section><nav className="driver-tabs" aria-label="Driver workspace tabs">{tabs.map(([name, subtitle]) => <button className={active === name ? 'active' : ''} onClick={() => setActive(name)} aria-current={active === name ? 'page' : undefined} key={name}><b>{name}</b><span>{subtitle}</span></button>)}</nav>{panelError && <div className="warning-note" role="alert">{panelError}</div>}{workspaceLoading && rider ? <div className="rider-workspace-loading">Refreshing {rider.name}'s workspace…</div> : panel}{showOnboarding && <DriverOnboardingModal onClose={() => setShowOnboarding(false)} onCreated={created} />}</div>;
}
