import { useEffect, useState } from 'react';
import { hubService, merchantService } from '../../services/resource.service';
import { useAuth } from '../../state/AuthContext';
import { isHubManager } from '../../config/roles';

const initial={hubId:'',businessName:'',shopName:'',buildingName:'',phone:'',email:'',address:'',password:'',referralCode:'',whatsapp:'',tiktok:'',instagram:'',facebook:'',startingLevel:'Starter'};
const fields=[['Business Name','businessName'],['Shop Name','shopName'],['Building Name','buildingName'],['Phone Number','phone','tel'],['Email','email','email'],['Address','address'],['Temporary Password','password','password'],['Referral Code (Optional)','referralCode','text',false],['WhatsApp Channel','whatsapp','text',false,'+256761253001 or wa.me link'],['TikTok Channel','tiktok','text',false,'@shophandle or TikTok URL'],['Instagram Channel','instagram','text',false,'@shophandle or Instagram URL'],['Facebook Channel','facebook','text',false,'Page name or Facebook URL']];
export function AddMerchantModal({onClose,onCreated}){
  const{user}=useAuth(),hubManager=isHubManager(user);
  const[form,setForm]=useState(initial),[hubs,setHubs]=useState([]),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(hubManager){setHubs([{_id:user.hubId,name:'Assigned hub',code:user.hubId}]);setForm(current=>({...current,hubId:user.hubId}));return undefined}const controller=new AbortController();hubService.list({status:'Active'},controller.signal).then(items=>{setHubs(items);setForm(current=>({...current,hubId:current.hubId||items[0]?._id||''}))}).catch(()=>setError('Active hubs could not be loaded.'));return()=>controller.abort()},[hubManager,user?.hubId]);
  useEffect(()=>{const close=e=>e.key==='Escape'&&onClose();document.addEventListener('keydown',close);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',close);document.body.style.overflow=previous}},[onClose]);
  const change=e=>setForm(current=>({...current,[e.target.name]:e.target.value}));
  async function submit(e){e.preventDefault();setSubmitting(true);setError('');try{const created=await merchantService.onboard({businessName:form.businessName.trim(),shopName:form.shopName.trim(),buildingName:form.buildingName.trim(),phone:form.phone.trim(),email:form.email.trim(),address:form.address.trim(),password:form.password,...(hubManager?{}:{hubId:form.hubId}),referralCode:form.referralCode.trim()||undefined,startingLevel:form.startingLevel,social:{whatsapp:form.whatsapp.trim(),tiktok:form.tiktok.trim(),instagram:form.instagram.trim(),facebook:form.facebook.trim()}});onCreated(created)}catch(err){setError(err.response?.data?.message||'Merchant could not be registered. Check the details and try again.')}finally{setSubmitting(false)}}
  return <div className="merchant-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="merchant-modal" onSubmit={submit}><header><h2><span aria-hidden="true">♙</span> Add New Merchant</h2><button type="button" onClick={onClose} aria-label="Close">×</button></header><main><label className="merchant-hub-field">Operational Hub{hubManager?<input value={user.hubId} readOnly aria-label="Assigned hub"/>:<select name="hubId" value={form.hubId} onChange={change} required><option value="">Select active hub</option>{hubs.map(hub=><option value={hub._id} key={hub._id}>{hub.name} - {hub.code} ({[hub.city,hub.zone].filter(Boolean).join(', ')})</option>)}</select>}<small>The backend assigns this record to the authenticated hub scope.</small></label><div className="merchant-modal-grid">{fields.map(([label,name,type='text',required=true,placeholder=''])=><label key={name}>{label}<input name={name} type={type} value={form[name]} onChange={change} required={required} placeholder={placeholder} minLength={name==='password'?8:undefined}/></label>)}</div><label className="merchant-level-field">Starting Level<select name="startingLevel" value={form.startingLevel} onChange={change}>{['Starter','Active','Priority','Elite'].map(level=><option key={level}>{level}</option>)}</select></label>{error&&<div className="merchant-modal-error">{error}</div>}</main><footer><button type="button" onClick={onClose}>Cancel</button><button className="register" disabled={submitting||!hubs.length}>{submitting?'Registering Merchant...':'Register Merchant'}</button></footer></form></div>;
}
