import { useCallback, useState } from 'react';
import { useApiQuery } from '../../hooks/useApiQuery';
import { reportService } from '../../services/resource.service';

const tabs=['Overview','Driver Performance','COD Reconciliation','Zone Heatmap','Customer Reports'];
const money=value=>`UGX ${Number(value||0).toLocaleString()}`;
function Scope(){return <div className="report-scope"><b>Scope:</b>&nbsp; All hubs | <b>Period:</b>&nbsp; All database records</div>}
function Metric({label,value,note,tone=''}){return <div className="report-metric"><span className={tone}>{label}</span><b className={tone}>{value}</b><small>{note}</small></div>}
function EmptyBox({title,body}){return <div className="report-empty"><b>DB</b><h3>{title}</h3><p>{body}</p></div>}
function Trend({daily=[]}){const max=Math.max(1,...daily.map(x=>x.orders));const points=daily.map((x,i)=>`${daily.length===1?500:i/(daily.length-1)*1000},${220-x.orders/max*210}`).join(' ');return <div className="report-line-chart"><div className="chart-y"><span>{max}</span><span>{Math.round(max*.75)}</span><span>{Math.round(max*.5)}</span><span>{Math.round(max*.25)}</span><span>0</span></div><div className="chart-plot"><i/><i/><i/><i/><i/><svg viewBox="0 0 1000 220" preserveAspectRatio="none"><polyline className="chart-line-path" points={points||'0,220 1000,220'}/></svg><div className="chart-x">{daily.map(x=><span key={x._id}>{x._id.slice(5)}</span>)}</div></div></div>}
function Overview({data}){const hubs=data.hubs||[],ratings=(data.riders||[]).map(x=>x.rating),rating=ratings.length?(ratings.reduce((a,b)=>a+b,0)/ratings.length).toFixed(1):0;return <><Scope/><div className="report-metrics five"><Metric label="Total Orders" value={data.totalOrders} note="Database order count" tone="purple"/><Metric label="Revenue" value={money(data.revenue)} note="Delivered fees" tone="green"/><Metric label="Avg Delivery Time" value={`${data.avgDeliveryMinutes||0} min`} note="Created to delivered" tone="violet"/><Metric label="Avg Rider Rating" value={`${rating}/5`} note={`${ratings.length} riders`} tone="orange"/><Metric label="Failed Rate" value={`${data.failedRate||0}%`} note="Failed order ratio" tone="red"/></div><section className="report-panel volume"><h3>Order Volume & Revenue</h3><Trend daily={data.daily}/><div className="chart-legend"><i/> Orders</div></section><div className="report-two"><section className="report-panel"><h3>Status Mix</h3><div className="status-mix-grid">{['Pending','Picked Up','At Hub','Out for Delivery','Delivered','Failed','Returned'].map(x=><p key={x}><span>{x}</span><b>{data.statusMix?.[x]||0}</b></p>)}</div></section><section className="report-panel"><h3>Cross-Hub Visibility</h3><div className="hub-report-list">{hubs.map(x=><p key={x._id}><b>{x.name}</b><span>{x.status}</span></p>)}</div></section></div></>}
function Drivers({data}){return <><Scope/><section className="report-panel driver-board"><h3>Driver Leaderboard</h3><div className="driver-head"><span>#</span><span>Driver</span><span>Status</span><span>Deliveries</span><span>Acceptance</span><span>Rating</span><span>COD Held</span></div>{(data.riders||[]).map((r,i)=><div className="driver-row" key={r._id}><span>{i+1}</span><span><b>{r.name}</b><small>{r.vehicleType} | {r.riderCode}</small></span><span>{r.availability}</span><span>{r.completedDeliveries}</span><span>{r.acceptanceRate}%</span><span>{r.rating}/5</span><span>{money(r.codHeld)}</span></div>)}</section></>}
function Cod({data}){const cod=data.cod||{};return <><Scope/><div className="report-metrics four"><Metric label="Order COD" value={money(cod.total)} note="All COD orders" tone="orange"/><Metric label="COD in Field" value={money(cod.inField)} note="Active COD orders" tone="purple"/><Metric label="COD Settled" value={money(cod.settled)} note="Delivered COD" tone="green"/><Metric label="Pending Withdrawals" value="UGX 0" note="No payout records" tone="red"/></div><div className="report-two cod-empty"><section className="report-panel"><h3>Rider COD / Payout Balances</h3><EmptyBox title="Tracked on rider records" body={`${(data.riders||[]).filter(x=>x.codHeld>0).length} riders currently hold COD.`}/></section><section className="report-panel"><h3>Settlement Records</h3><EmptyBox title="No settlement history" body="A settlement ledger can be added when the payout provider is selected."/></section></div></>}
function Zones({data}){const zones=data.zones||[];return <><Scope/><div className="zone-metrics">{zones.map((z,i)=><Metric key={z.name} label={z.name} value={`${z.successRate}%`} note={`${z.orders} orders`} tone={i%2?'green':'purple'}/>)}</div><section className="report-panel volume"><h3>Zone Success Comparison</h3><div className="status-mix-grid">{zones.map(z=><p key={z.name}><span>{z.name}</span><b>{z.delivered}/{z.orders} delivered</b></p>)}</div></section></>}
function Customers({data}){const repeat=data.uniqueCustomers?Math.round(data.repeatCustomers/data.uniqueCustomers*100):0;return <><Scope/><div className="report-metrics four"><Metric label="Unique Customers" value={data.uniqueCustomers} note="From phone numbers"/><Metric label="Repeat Customers" value={`${repeat}%`} note={`${data.repeatCustomers} repeat customers`} tone="green"/><Metric label="Avg Orders / Customer" value={data.avgOrdersPerCustomer} note="Orders in period" tone="purple"/><Metric label="Failed Customer Orders" value={data.failedCustomerOrders} note="Failed records" tone="red"/></div><section className="support-pipeline"><h3>Support Complaint Pipeline</h3><p>Support tickets are stored by the backend and available to administrators.</p><b>Connected to support API</b></section></>}
export function ReportsPage(){const[tab,setTab]=useState('Overview'),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');const loader=useCallback(signal=>reportService.get(signal),[]);const{data={hubs:[],riders:[],zones:[],daily:[]}}=useApiQuery(loader,{});async function exportCsv(){setExporting(true);setExportError('');try{await reportService.export('csv')}catch(err){setExportError(err.response?.data?.message||'Report export failed.')}finally{setExporting(false)}}return <div className="reports-page"><div className="reports-controls"><div>{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><button className="export-report" disabled={exporting} onClick={exportCsv}>{exporting?'Exporting...':'Export CSV'}</button></div><main className="reports-content">{exportError&&<div className="warning-note">{exportError}</div>}{tab==='Overview'&&<Overview data={data}/>} {tab==='Driver Performance'&&<Drivers data={data}/>} {tab==='COD Reconciliation'&&<Cod data={data}/>} {tab==='Zone Heatmap'&&<Zones data={data}/>} {tab==='Customer Reports'&&<Customers data={data}/>}</main></div>}
