import { useEffect, useMemo, useRef, useState } from 'react';
import { merchantService } from '../../services/resource.service';
import { orderService } from '../../services/order.service';

const steps=[['Merchant','Who sends it.'],['Customer','Receiver details.'],['Package','Size and zone.'],['Payment','COD and auto fee.'],['Hub Intake','Scan before rider.']];
const initial={merchantId:'',customer:'',phone:'',customerEmail:'',pickupLocation:'',dropoffLocation:'',pickupLat:'',pickupLng:'',dropoffLat:'',dropoffLng:'',gpsOpen:false,zone:'',batchGroup:'',itemDescription:'',packageSize:'Medium',serviceType:'Standard',notes:'',value:0,codAmount:0,fee:0,distanceKm:0,insuranceEnabled:false,coverageAmount:0};

function Picker({items,value,onChange}){
  const[open,setOpen]=useState(false),ref=useRef(null),selected=items.find(item=>item._id===value);
  useEffect(()=>{const close=event=>!ref.current?.contains(event.target)&&setOpen(false);document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
  return <div className={`merchant-picker ${open?'open':''}`} ref={ref}>
    <button type="button" className="merchant-picker-trigger" onClick={()=>setOpen(current=>!current)}><span>{selected?.name||'Select merchant'}</span><i>⌄</i></button>
    {open&&<div className="merchant-picker-menu"><button type="button" onClick={()=>{onChange('');setOpen(false)}}><span>Select merchant</span>{!value&&<b>✓</b>}</button>{items.map(item=><button type="button" disabled={item.locked} onClick={()=>{onChange(item._id);setOpen(false)}} key={item._id}><span>{item.name}{item.locked?' - blocked':''}</span>{value===item._id&&<b>✓</b>}</button>)}<div className="merchant-picker-tail">⌄</div></div>}
  </div>;
}
function Field({label,children,className=''}){return <label className={className}>{label}{children}</label>}

export function NewOrderModal({onClose,onCreate}){
  const[step,setStep]=useState(0),[merchants,setMerchants]=useState([]),[form,setForm]=useState(initial),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false),[quoting,setQuoting]=useState(false);
  useEffect(()=>{const controller=new AbortController();merchantService.list({},controller.signal).then(setMerchants).catch(err=>setError(err.response?.data?.message||'Merchants could not be loaded.'));return()=>controller.abort()},[]);
  useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[]);
  const merchant=useMemo(()=>merchants.find(item=>item._id===form.merchantId),[merchants,form.merchantId]);
  const change=event=>setForm(current=>({...current,[event.target.name]:event.target.type==='checkbox'?event.target.checked:['value','codAmount','coverageAmount'].includes(event.target.name)?Number(event.target.value):event.target.value}));
  const coords=(lat,lng)=>lat!==''&&lng!==''?{latitude:Number(lat),longitude:Number(lng)}:undefined;
  async function quote(){setQuoting(true);setError('');try{const data=await orderService.quote({distanceKm:Number(form.distanceKm)||0,codAmount:form.codAmount,insurance:form.insuranceEnabled,serviceType:form.serviceType.toUpperCase()});setForm(current=>({...current,fee:data.total}))}catch(err){setError(err.response?.data?.message||'Delivery fee could not be calculated.')}finally{setQuoting(false)}}
  function next(){if(step===0&&!merchant)return setError('Select an active merchant.');if(step===1&&(!form.customer||!form.phone||!form.pickupLocation||!form.dropoffLocation))return setError('Complete customer, pickup, and drop-off fields.');if(step===2&&(!form.zone||!form.itemDescription))return setError('Complete zone and item description.');if(step===3&&form.insuranceEnabled&&form.coverageAmount<=0)return setError('Enter the insurance coverage amount.');setError('');setStep(current=>Math.min(4,current+1))}
  async function submit(){setSubmitting(true);setError('');try{await onCreate({hubId:String(merchant.hubId),merchantId:form.merchantId,customer:{name:form.customer.trim(),phone:form.phone.trim(),email:form.customerEmail.trim()||undefined},pickup:{address:form.pickupLocation.trim(),location:coords(form.pickupLat,form.pickupLng)},delivery:{address:form.dropoffLocation.trim(),instructions:form.notes.trim()||undefined,location:coords(form.dropoffLat,form.dropoffLng)},itemDescription:form.itemDescription.trim(),declaredValue:Number(form.value)||0,paymentMethod:form.codAmount>0?'COD':'PREPAID',codAmount:Number(form.codAmount)||0,insurance:form.insuranceEnabled,serviceType:form.serviceType.toUpperCase(),distanceKm:Number(form.distanceKm)||0,packageSize:form.packageSize.toUpperCase(),batchGroup:form.batchGroup.trim()||undefined});onClose()}catch(err){setError(err.response?.data?.message||'Order could not be created.')}finally{setSubmitting(false)}}

  return <div className="new-order-backdrop"><section className="new-order-modal">
    <header><h2><span>＋</span> Create New Order</h2><button onClick={onClose}>×</button></header>
    <div className="order-step-tabs">{steps.map(([title,note],index)=><button type="button" className={index<step?'complete':index===step?'active':''} onClick={()=>index<step&&setStep(index)} key={title}><i>{index<step?'✓':index+1}</i><b>{title}</b><span>{note}</span></button>)}</div>
    <main>
      <p>{['Choose the merchant first so the order can attach to the correct account and hub context.','Pickup and drop-off locations drive the automatic Wolan KM-based delivery fee.','Package size affects rider compatibility, so keep it explicit before auto-dispatch.','Delivery fee is backend-calculated from GPS distance. Admin and merchants cannot edit it manually.','Review and create. Merchant handover and hub scan remain required before rider assignment.'][step]}</p>
      {step===0&&<Field label="Merchant"><Picker items={merchants} value={form.merchantId} onChange={merchantId=>setForm(current=>({...current,merchantId}))}/></Field>}
      {step===1&&<div className="customer-step">
        <Field label="Customer Name"><input name="customer" value={form.customer} onChange={change}/></Field><Field label="Customer Phone"><input type="tel" name="phone" value={form.phone} onChange={change}/></Field><Field label="Customer Email (optional)"><input type="email" name="customerEmail" value={form.customerEmail} onChange={change}/></Field>
        <Field label="Pickup Location"><div className="lookup-field"><input name="pickupLocation" value={form.pickupLocation} onChange={change}/><button type="button" onClick={()=>setForm(current=>({...current,gpsOpen:true}))}>Lookup</button></div></Field>
        <Field label="Drop-off Location"><div className="lookup-field"><input name="dropoffLocation" value={form.dropoffLocation} onChange={change}/><button type="button" onClick={()=>setForm(current=>({...current,gpsOpen:true}))}>Lookup</button></div></Field>
        <button type="button" className="gps-toggle" onClick={()=>setForm(current=>({...current,gpsOpen:!current.gpsOpen}))}><span>⌾ &nbsp; Optional GPS override</span><small>Map provider resolves blank fields</small></button>
        {form.gpsOpen&&<div className="gps-grid"><input type="number" step="any" min="-90" max="90" name="pickupLat" value={form.pickupLat} onChange={change} placeholder="Pickup latitude"/><input type="number" step="any" min="-180" max="180" name="pickupLng" value={form.pickupLng} onChange={change} placeholder="Pickup longitude"/><input type="number" step="any" min="-90" max="90" name="dropoffLat" value={form.dropoffLat} onChange={change} placeholder="Drop-off latitude"/><input type="number" step="any" min="-180" max="180" name="dropoffLng" value={form.dropoffLng} onChange={change} placeholder="Drop-off longitude"/></div>}
      </div>}
      {step===2&&<div className="new-order-fields"><Field label="Zone"><input name="zone" value={form.zone} onChange={change}/></Field><Field label="Batch Group (Optional)"><input name="batchGroup" value={form.batchGroup} onChange={change} placeholder="Example: KLA-MORNING-01"/></Field><Field label="Item Description"><input name="itemDescription" value={form.itemDescription} onChange={change}/></Field><Field label="Package Size"><select name="packageSize" value={form.packageSize} onChange={change}><option>Small</option><option>Medium</option><option>Large</option></select></Field><Field label="Delivery Notes (Optional)" className="full"><textarea name="notes" value={form.notes} onChange={change} placeholder="Handling or delivery instructions"/></Field></div>}
      {step===3&&<div className="payment-step"><div className="new-order-fields"><Field label="Declared Value"><input type="number" name="value" min="0" value={form.value} onChange={change}/></Field><Field label="COD Amount"><input type="number" name="codAmount" min="0" value={form.codAmount} onChange={change}/></Field><Field label="Service Level"><select name="serviceType" value={form.serviceType} onChange={change}><option value="Standard">Standard delivery</option><option value="Express">Express delivery</option></select></Field><Field label="Insurance"><label className="insurance-toggle"><input type="checkbox" name="insuranceEnabled" checked={form.insuranceEnabled} onChange={change}/> Add delivery coverage</label></Field>{form.insuranceEnabled&&<Field label="Coverage Amount" className="full"><input type="number" name="coverageAmount" min="0" value={form.coverageAmount} onChange={change}/></Field>}</div><div className="hub-sop"><b>Hub-first dispatch SOP</b><span>This order will be created without a rider. Merchant handover and confirmed hub scan-in must be completed before assignment unlocks.</span></div><button type="button" className="calculate-fee" onClick={quote} disabled={quoting}>{quoting?'Calculating...':'Calculate delivery fee'}</button><div className="fee-result"><span>AUTOMATIC WOLAN PRICING</span><b>UGX {Number(form.fee).toLocaleString()}</b><small>{form.distanceKm?`${form.distanceKm} KM route`:'Enter GPS coordinates, then calculate fee.'}</small></div></div>}
      {step===4&&<div className="order-review"><p><span>Merchant</span><b>{merchant?.name}</b></p><p><span>Customer</span><b>{form.customer} · {form.phone}</b></p><p><span>Route</span><b>{form.pickupLocation} → {form.dropoffLocation}</b></p><p><span>Package</span><b>{form.itemDescription} · {form.packageSize}</b></p><p><span>Payment</span><b>COD UGX {form.codAmount.toLocaleString()} · Fee UGX {form.fee.toLocaleString()}</b></p>{form.insuranceEnabled&&<p><span>Insurance</span><b>UGX {form.coverageAmount.toLocaleString()} coverage</b></p>}</div>}
      {error&&<div className="warning-note">{error}</div>}
    </main>
    <footer><button onClick={onClose}>Cancel</button><button disabled={!step} onClick={()=>setStep(current=>current-1)}>← Back</button>{step<4?<button className="primary" onClick={next}>Continue →</button>:<button className="primary" disabled={submitting} onClick={submit}>{submitting?'Creating...':'Create Order'}</button>}</footer>
  </section></div>;
}
