import { useEffect, useState } from 'react';
import { adminService, settingService } from '../../services/resource.service';

const sections=['Business','Regional Ops','Dispatch','Notifications','Team & Users','Security','Branding','Integrations','Billing','Support'];
const field=(label,value)=><label key={label}>{label}<input name={label.toLowerCase().replace(/[^a-z0-9]+/g,'_')} defaultValue={value}/></label>;
function Panel({title,children,action=true}){const[message,setMessage]=useState('');async function save(event){const section=event.currentTarget.closest('section');const values={};section.querySelectorAll('input').forEach((input,index)=>{values[input.name||`field_${index}`]=input.value;});try{await settingService.save({[title]:values});setMessage('Saved');}catch{setMessage('Save failed');}}return <section className="settings-panel"><header><h2>{title}</h2></header>{children}{action&&<button className="settings-save" onClick={save}>Save Changes</button>}{message&&<small>{message}</small>}</section>}
function Toggle({label,note,on=true}){const[enabled,setEnabled]=useState(on);return <div className="setting-toggle"><p><b>{label}</b><span>{note}</span></p><button className={enabled?'on':''} onClick={()=>setEnabled(!enabled)}><i/></button></div>}
function Business(){return <><Panel title="Business Information"><div className="settings-fields three">{[['Company Name','Wolan Logistics SMC Ltd'],['Trading Name','Wolan Logistics'],['TIN / Tax ID','1008765432'],['Country','Uganda'],['City','Kampala'],['Main Hub Address','Pioneer Mall, Ntinda'],['Support Phone','+256 761 253001'],['Support Email','']].map(x=>field(...x))}</div></Panel><Panel title="Operating Hours"><div className="settings-fields three">{[['Monday - Friday','07:00 - 21:00'],['Saturday','07:00 - 21:00'],['Sunday','Closed']].map(x=>field(...x))}</div></Panel></>}
function Regional(){return <Panel title="Currency, Location & Regional Operations"><div className="regional-layout"><div className="settings-subpanel"><h3>Currency Selection</h3>{field('Active currency','UGX - Ugandan Shilling')}<div className="source-truth"><span>Current Source of Truth</span><b>UGX</b></div></div><div className="settings-subpanel"><h3>Location Configuration</h3><div className="settings-fields three">{[['Country','Uganda'],['Country Code','UG'],['Phone Prefix','+256'],['Primary City','Kampala'],['Operating Region','Kampala Metropolitan'],['Timezone','Africa/Kampala'],['Default Latitude','0.3476'],['Default Longitude','32.5825'],['Map Display Radius','25']].map(x=>field(...x))}</div></div></div><div className="pricing-box"><h3>Configurable Distance Pricing</h3>{[[0,1,2500,'0-1 KM'],[1,3,5000,'1-3 KM']].map((r,i)=><div className="pricing-row" key={i}>{r.map((v,j)=>field(['Min KM','Max KM','Fee (UGX)','Label'][j],v))}<button>Delete</button></div>)}</div></Panel>}
function Dispatch(){return <><Panel title="Dispatch Configuration"><div className="settings-fields three">{[['Max Orders per Rider','8'],['Delivery ETA Default (min)','45'],['Stage Assignment Zone Radius (km)','3'],['Idle Alert Threshold (min)','15'],['GPS Dark Alert Threshold (min)','10'],['COD Remit Deadline (hrs)','24']].map(x=>field(...x))}</div></Panel><Panel title="Auto-Dispatch Rules">{[['Auto-assign nearest available rider','Dispatch uses rider availability and distance'],['Prioritize Elite merchant orders','Elite merchant orders stay ahead in the queue'],['Block offline riders from new assignments','Offline riders cannot receive new delivery work'],['Allow rider self-assignment via app','Riders can claim compatible open orders']].map(x=><Toggle label={x[0]} note={x[1]} key={x[0]}/>)}</Panel></>}
function NotificationSettings(){return <><Panel title="Notification Preferences">{[['New Order Alert','Notify dispatchers when a new order is placed',1],['Failed Delivery SMS','Send SMS to customer when delivery fails',1],['GPS Dark Alert','Alert when rider GPS goes offline',1],['COD Overdue Alert','Alert when COD not remitted after 24 hours',1],['Rider Check-In','Notify hub manager when rider checks in',0],['Daily Report Email','Send daily summary report to manager email',1],['Low Rider Count','Alert when available riders drop below threshold',0]].map(x=><Toggle label={x[0]} note={x[1]} on={!!x[2]} key={x[0]}/>)}</Panel><Panel title="Alert Channels">{['SMS','WhatsApp Notifications','Email Reports'].map(x=><Toggle label={x} note="Operational notification channel" key={x}/>)}</Panel></>}
function Team(){const[users,setUsers]=useState([]);useEffect(()=>{const controller=new AbortController();adminService.users(controller.signal).then(setUsers).catch(()=>{});return()=>controller.abort()},[]);async function toggle(user){const updated=await adminService.updateUser(user._id,{locked:!user.locked,status:user.locked?'Active':'Suspended'});setUsers(items=>items.map(item=>item._id===updated._id?updated:item))}return <><Panel title="Team Members" action={false}><div className="team-list">{users.map(user=><div key={user._id}><i>{user.name.slice(0,2)}</i><p><b>{user.name}</b><span>{user.email}</span></p><em>{user.role}</em><span>{user.status}</span><button onClick={()=>toggle(user)}>{user.locked?'Unlock':'Suspend'}</button></div>)}</div></Panel><Panel title="Role Permissions" action={false}><p>Admins manage the full network, users, settings, and hub assignments.</p><p>Dispatchers operate orders and notifications without administrative user access.</p></Panel></>}
function Security(){return <><Panel title="Account email"><div className="settings-fields two">{field('Current email','admin@wolan.com')}{field('New email','name@example.com')}</div></Panel><Panel title="Account password"><div className="settings-fields three">{field('Current password','')}{field('New password','')}{field('Confirm password','')}</div></Panel><Panel title="Security & Access">{[['Two-Factor Authentication','Require 2FA for all admin logins',0],['Session Timeout (30 min)','Auto-logout after inactivity',1],['Login IP Whitelist','Only allow logins from approved IPs',0]].map(x=><Toggle label={x[0]} note={x[1]} on={!!x[2]} key={x[0]}/>)}</Panel></>}
function Branding(){return <Panel title="Brand Customization"><div className="brand-preview"><div className="brand-mark">W</div><p><b>Wolan Logistics</b><span>Current logo</span><a>Upload new logo</a></p></div><div className="settings-fields three">{field('Primary Color','#4B0082')}{field('Brand Background','#F8F7FB')}{field('Card Color','#FFFFFF')}</div></Panel>}
function Integrations(){return <Panel title="Third-Party Integrations" action={false}><div className="integration-list">{[['Africa\'s Talking SMS','Sandbox configured'],['Mapbox Traffic / Mapbox Maps','Configured'],['Traccar GPS','Not available for Phase 1'],['Mictrack Device API','Deferred until handover'],['Flutterwave Payments','Deferred until handover'],['Hetzner KYC Storage','Local storage active'],['Support Channels','Configured for live testing']].map(x=><div key={x[0]}><p><b>{x[0]}</b><span>Provider configuration and operational usage details.</span></p><strong>{x[1]}</strong><button>View</button></div>)}</div></Panel>}
function Billing(){return <Panel title="Subscription & Billing"><div className="billing-banner"><p><b>Provider-managed billing</b><span>Live usage counters appear when billing providers expose reporting APIs.</span></p><h3>Configured externally</h3></div>{['SMS / WhatsApp Provider','Email Provider','KYC Storage'].map(x=><p className="billing-row" key={x}><span>{x}</span><b>Configured</b></p>)}</Panel>}
function Support(){const[message,setMessage]=useState('');async function submit(e){e.preventDefault();const data=new FormData(e.currentTarget);try{await adminService.createTicket({subject:data.get('subject'),message:data.get('message')});setMessage('Support ticket created.');e.currentTarget.reset()}catch{setMessage('Support ticket could not be created.')}}return <Panel title="Admin support shortcuts" action={false}><div className="support-cards">{['WhatsApp','Voice Call','Email'].map(x=><div key={x}><b>{x}</b><span>+256 761 253001</span></div>)}</div><form className="support-ticket" onSubmit={submit}><label>Subject<input name="subject" required/></label><textarea name="message" required placeholder="Describe the issue, order ID, rider, merchant, or page where help is needed."/><button>Create support ticket</button></form>{message&&<small>{message}</small>}</Panel>}

export function SettingsPage(){const[active,setActive]=useState('Business');const content={'Business':<Business/>,'Regional Ops':<Regional/>,'Dispatch':<Dispatch/>,'Notifications':<NotificationSettings/>,'Team & Users':<Team/>,'Security':<Security/>,'Branding':<Branding/>,'Integrations':<Integrations/>,'Billing':<Billing/>,'Support':<Support/>};return <div className="settings-page-v2"><aside className="settings-nav">{sections.map((x,i)=><button className={active===x?'active':''} onClick={()=>setActive(x)} key={x}><span>{i+1}</span>{x}</button>)}</aside><main className="settings-content">{content[active]}</main></div>}
