import { useState } from 'react';
import { useDemo } from '../../state/DemoContext';

export function MerchantsPage() {
  const { orders } = useDemo();
  const merchants = [
    { name: 'Pioneer Tech Hub', tier: 'Elite', code: 'WOL-PTH-82', orders: 284, payout: 'UGX 1,420,000' },
    { name: 'Kampala Phone Point', tier: 'Priority', code: 'WOL-KPP-14', orders: 126, payout: 'UGX 680,000' },
    { name: 'Ntinda Home Store', tier: 'Active', code: 'WOL-NHS-31', orders: 73, payout: 'UGX 325,000' },
  ];
  return <div><section className="page-intro"><div><span className="eyebrow">Merchant network</span><h2>Merchants</h2><p>Profiles, portal access, COD payouts, referral codes, and order visibility.</p></div><button className="primary-button">+ Add merchant</button></section><div className="merchant-grid">{merchants.map(merchant => <section className="merchant-card" key={merchant.name}><div className="merchant-top"><div className="merchant-avatar">{merchant.name.split(' ').map(x => x[0]).join('').slice(0,2)}</div><span className="tier-badge">{merchant.tier}</span></div><h3>{merchant.name}</h3><p>Pioneer Mall, Kampala</p><div className="merchant-metrics"><div><span>Total deliveries</span><b>{merchant.orders}</b></div><div><span>COD payout due</span><b>{merchant.payout}</b></div></div><div className="referral-code"><span>M2M referral code</span><b>{merchant.code}</b></div><button>Open merchant workspace</button></section>)}</div><section className="portal-preview"><div><span className="eyebrow">Merchant app preview</span><h2>Pickup key is visible at handover</h2><p>This closes P0 issue WOL-002. The merchant can show the one-time key to the authorized pickup agent, while tracking every active order.</p></div><div className="phone-preview"><div className="phone-notch"/><span>Active pickup</span><h3>{orders[0]?.id}</h3><p>Show this one-time code to the pickup agent</p><b>{orders[0]?.pickupKey}</b><small>Never share the key by phone or chat.</small></div></section></div>;
}

export function HubsPage() {
  const { hubs, selectedHub, setSelectedHub } = useDemo();
  const [showForm, setShowForm] = useState(false);
  return <div><section className="page-intro"><div><span className="eyebrow">Multi-tenant operations</span><h2>Hub management</h2><p>One platform, isolated hub data, and HQ oversight.</p></div><button className="primary-button" onClick={() => setShowForm(!showForm)}>+ Add new hub</button></section>{showForm && <section className="new-hub-form"><h3>Create an isolated hub</h3><input placeholder="Hub name"/><input placeholder="Location"/><input placeholder="Zone coverage"/><button onClick={() => setShowForm(false)}>Generate next Hub ID</button></section>}<div className="hub-grid">{hubs.map(hub => <button className={`hub-card ${selectedHub === hub.id ? 'selected' : ''}`} onClick={() => setSelectedHub(hub.id)} key={hub.id}><div><span>{hub.id}</span><b className="active-dot">{hub.status}</b></div><h3>{hub.name}</h3><p>{hub.city} - isolated operational tenant</p><div className="hub-progress"><i style={{ width: `${Math.round(hub.deliveries / hub.target * 100)}%` }}/></div><footer><b>{hub.deliveries} deliveries</b><span>{Math.round(hub.deliveries / hub.target * 100)}% of target</span></footer></button>)}</div><section className="isolation-rules"><h3>Data isolation controls</h3><div><p><b>Hub managers</b><span>See only orders, riders, merchants, COD and maps tagged with their hub_id.</span></p><p><b>Regional managers</b><span>See only their assigned group of hubs.</span></p><p><b>HQ leadership</b><span>Can compare all hubs and drill into an isolated hub workspace.</span></p></div></section></div>;
}

export function NotificationsPage() { const alerts = [['Package/rider mismatch','PKG-001-0712 moved 620m away from rider GPS','Critical'],['Rider GPS stale','Hazaf has not sent a location update for 16 minutes','Critical'],['COD threshold warning','Sarah N. is carrying UGX 870,000','Warning'],['Daily summary ready','Pioneer Mall hub closed at 61% of today\'s target','Info']]; return <div><section className="page-intro"><div><span className="eyebrow">Operations inbox</span><h2>Notifications</h2><p>Realtime safety, custody, COD, and delivery alerts.</p></div><button className="secondary-button">Mark all reviewed</button></section><section className="notification-list">{alerts.map(([title, body, tone]) => <div key={title}><i className={tone.toLowerCase()}/><div><h3>{title}</h3><p>{body}</p></div><span>{tone}</span><button>Review</button></div>)}</section></div>; }

export function ReportsPage() { return <div><section className="page-intro"><div><span className="eyebrow">Evidence and analytics</span><h2>Reports</h2><p>Revenue, delivery performance, COD reconciliation, and release evidence.</p></div><button className="primary-button">Export CSV</button></section><div className="report-grid">{[['Revenue this week','UGX 8.42M','+14.2%'],['Completion rate','96.8%','+2.1%'],['COD reconciled','UGX 6.7M','100% settled'],['Average delivery','42 min','3 min faster']].map(item => <section className="report-stat" key={item[0]}><span>{item[0]}</span><b>{item[1]}</b><small>{item[2]}</small></section>)}</div><section className="evidence-table"><div><h3>Deployment evidence register</h3><span>Phase 1 selection build</span></div>{[['WOL-001','Mandatory hub scan before assignment','Demo verified'],['WOL-002','Merchant pickup key handover','Demo verified'],['WOL-004','Customer OTP before completion','Demo verified'],['WOL-006','Realtime dashboard updates','Frontend simulated'],['WOL-008','Map details after selection','Demo verified']].map(row => <p key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><strong>{row[2]}</strong></p>)}</section></div>; }

export function SettingsPage() { return <div><section className="page-intro"><div><span className="eyebrow">Platform configuration</span><h2>Settings</h2><p>Business, dispatch, rider, communication, and security controls.</p></div><button className="primary-button">Save changes</button></section><div className="settings-grid">{[['Dispatch controls','Auto-assign nearest eligible rider','Require proof of delivery','7 minute rider response window'],['Customer communication','SMS dispatch notifications','Secure tracking links','24-hour rating request'],['Financial controls','10% COD service fee','UGX 1,000,000 rider COD limit','8:00 PM merchant payout'],['Security controls','Mandatory hub scan','500m package mismatch alert','15 minute GPS stale alert']].map(([title,...items]) => <section key={title}><h3>{title}</h3>{items.map((item,index) => <label key={item}><span>{item}</span><input type="checkbox" defaultChecked={index < 2}/></label>)}</section>)}</div></div>; }
