import api from './api';
const identity = value => value;
const resource = (path, normalize = identity) => ({ async list(params,signal){const{data}=await api.get(path,{params,signal});return (data?.items||data||[]).map(normalize);},async get(id){const{data}=await api.get(`${path}/${encodeURIComponent(id)}`);return normalize(data);},async create(payload){const{data}=await api.post(path,payload);return normalize(data);},async update(id,payload){const{data}=await api.patch(`${path}/${encodeURIComponent(id)}`,payload);return normalize(data);},async remove(id){await api.delete(`${path}/${encodeURIComponent(id)}`);} });
const normalizeHub = item => ({ ...item, id: item.hubId, operationalId: item.hubId, location: item.address || '', zone: item.zoneCoverage?.[0] || '', coordinates: item.location?.coordinates ? { lng: item.location.coordinates[0], lat: item.location.coordinates[1] } : undefined });
const normalizeMerchant = item => ({ ...item, name: item.businessName || item.shopName || item.merchantCode, owner: item.ownerName || '', tier: String(item.tier || 'STARTER').toLowerCase().replace(/^./, character => character.toUpperCase()), kycStatus: item.kycStatus === 'VERIFIED' ? 'KYC Verified' : 'KYC Needed', locked: item.status !== 'ACTIVE' });
const statusLabel = status => status === 'ACTIVE' ? 'KYC verified' : status === 'PENDING_KYC' ? 'KYC pending' : status === 'PENDING_LEGAL' ? 'Legal acceptance pending' : String(status || 'Pending').toLowerCase().split('_').map(word => word[0]?.toUpperCase() + word.slice(1)).join(' ');
const normalizeDriver = item => { const status=String(item.status||'PENDING_KYC').toUpperCase(),availability=String(item.availability||'OFFLINE').toUpperCase().replaceAll(' ','_'),coordinates=item.currentLocation?.coordinates;return{...item,status,availability,driverCode:item.driverCode||item.riderCode,locked:status!=='ACTIVE',kycStatus:statusLabel(status),acceptanceRate:Number(item.acceptanceRate??0),vehicleType:item.vehicle?.type||item.vehicleType||'',location:coordinates?{lng:coordinates[0],lat:coordinates[1],updatedAt:item.lastHeartbeatAt}:undefined}; };
const normalizeDriverWorkspace = data => ({...data,driver:normalizeDriver({...data.driver,email:data.user?.email||data.driver?.email,vehicle:data.vehicle})});
export const hubService=resource('/hubs', normalizeHub); export const riderService={...resource('/drivers', normalizeDriver),async availability(payload){const{data}=await api.post('/drivers/check-availability',payload);return data;},async onboard(payload){const{data}=await api.post('/drivers',payload);return normalizeDriver(data);},async workspace(id,signal){const{data}=await api.get(`/drivers/${encodeURIComponent(id)}/workspace`,{signal});return normalizeDriverWorkspace(data);}}; export const merchantService={...resource('/merchants', normalizeMerchant),async onboard(payload){const{data}=await api.post('/merchants',payload);return normalizeMerchant(data);}};
export const dashboardService={async get(signal){const{data}=await api.get('/dashboard',{signal});const title=value=>String(value||'').toLowerCase().split('_').map(word=>word[0].toUpperCase()+word.slice(1)).join(' ');const statusMix=Object.fromEntries(Object.entries(data.orderStats||{}).map(([status,value])=>[title(status),value.count]));const recentOrders=(data.recentOrders||[]).map(order=>({...order,id:order._id,merchant:order.merchantId?.businessName||order.merchantId?.shopName||order.merchantId,zone:order.delivery?.address,status:title(order.orderStatus),rider:order.driverId?.name,fee:order.pricing?.total,payment:order.paymentMethod,value:order.codAmount}));return{...data,statusMix,ordersToday:Object.values(data.orderStats||{}).reduce((sum,value)=>sum+value.count,0),onlineRiders:data.onlineDrivers,codInField:data.codExposure?.amount||0,failedToday:data.orderStats?.FAILED?.count||0,recentOrders,liveRiders:data.liveRiders||[]};}};
export const reportService={
  async get(signal,params){const{data}=await api.get('/reports/overview',{signal,params});const codRows=data.cod?.byStatus||[];return{...data,riders:data.riders||data.riderPerformance||[],zones:data.zones||(data.heatmaps||[]).map(row=>({...row,name:row.zone})),daily:data.daily||data.analytics?.daily||[],statusMix:data.statusMix||data.analytics?.statusMix||{},hubs:data.hubs||[],cod:{...data.cod,inField:codRows.filter(row=>!['SETTLED','RECONCILED'].includes(row._id)).reduce((sum,row)=>sum+row.amount,0),settled:codRows.filter(row=>['SETTLED','RECONCILED'].includes(row._id)).reduce((sum,row)=>sum+row.amount,0)},uniqueCustomers:data.customers?.unique||0,repeatCustomers:data.customers?.repeat||0,avgOrdersPerCustomer:data.customers?.averageOrders||0,failedCustomerOrders:data.customers?.failedOrders||0};},
  async export(format='csv',params={}){const response=await api.get('/reports/export',{params:{...params,format},responseType:'blob'});const disposition=response.headers['content-disposition']||'';const filename=disposition.match(/filename="?([^";]+)"?/i)?.[1]||`wolan-report.${format}`;const url=URL.createObjectURL(response.data);const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
};
export const settingService={async get(signal){const{data}=await api.get('/settings',{signal});return data;},async save(payload){const{data}=await api.put('/settings',payload);return data;}};
export const adminService={async users(signal){const{data}=await api.get('/users',{signal});return data?.items||data||[];},async createUser(payload){const{data}=await api.post('/users',payload);return data;},async updateUser(id,payload){const{data}=await api.patch(`/users/${encodeURIComponent(id)}`,payload);return data;},async tickets(signal){const{data}=await api.get('/tickets',{signal});return data?.items||data||[];},async createTicket(payload){const{data}=await api.post('/tickets',{...payload,priority:'NORMAL',status:'OPEN'});return data;}};
export const trackingService={async get(id,signal){const{data}=await api.get(`/orders/${encodeURIComponent(id)}`,{signal});return data;}};
export const uploadService={
  async files(files,folder='uploads'){const body=new FormData();for(const file of files)body.append('files',file);body.append('folder',folder);const{data}=await api.post('/upload',body,{headers:{'Content-Type':'multipart/form-data'}});return data;}
};
